openapi: 3.0.0
info:
  title: OTP Mobil Kft. Backend API
  description: REST API for computing trip profits.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Local development server
paths:
  /vehicles:
    post:
      tags:
        - Vehicles
      summary: Register a new vehicle
      description: Add a new vehicle with details such as passenger capacity, range, and fuel type.
      operationId: registerVehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleRequest'
      responses:
        '201':
          description: Vehicle added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleResponse'

    get:
      tags:
        - Vehicles
      summary: Retrieve all vehicles
      description: Get a list of all available vehicles.
      operationId: getAllVehicles
      responses:
        '200':
          description: List of available vehicles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleResponse'

components:
  schemas:
    VehicleRequest:
      type: object
      required:
        - passengerCapacity
        - rangeKm
        - fuelType
      properties:
        passengerCapacity:
          type: integer
          minimum: 1
          description: Maximum number of passengers
        rangeKm:
          type: number
          format: double
          description: Maximum range in kilometers
        fuelType:
          $ref: '#/components/schemas/FuelType'
        availableType:
          $ref: '#/components/schemas/AvailableType'
      example:
        passengerCapacity: 4
        rangeKm: 500.50
        fuelType: gasoline
        availableType: available

    VehicleResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: Auto-generated vehicle ID
        passengerCapacity:
          type: integer
        rangeKm:
          type: number
          format: double
        fuelType:
          $ref: '#/components/schemas/FuelType'
        availableType:
          $ref: '#/components/schemas/AvailableType'
      example:
        id: "550e8400-e29b-41d4-a716-446655440000"
        passengerCapacity: 4
        rangeKm: 500.50
        fuelType: gasoline
        availableType: available

    FuelType:
      type: string
      enum:
        - gasoline
        - hybrid
        - electric
      description: Type of fuel used by the vehicle

    AvailableType:
      type: string
      enum:
        - available
        - unavailable
      description: Type of fuel used by the vehicle